"""Add aliases for German team names and other common ones."""
import json
from pathlib import Path

# Lade bestehende aliases
p = Path("E:/Profilov2/public/data/wm-predictor/aliases.json")
data = json.loads(p.read_text())

# Neue Aliase hinzufuegen
new_aliases = {
    "kolumbien": "Colombia",
    "colombia": "Colombia",
    "mexiko": "Mexico",
    "mexico": "Mexico",
    "japan": "Japan",
    "kroatien": "Croatia",
    "südkorea": "South Korea",
    "südkorea": "South Korea",
    "suedkorea": "South Korea",
    "nordkorea": "North Korea",
    "tuerkei": "Turkey",
    "türkei": "Turkey",
    "schweden": "Sweden",
    "daenemark": "Denmark",
    "dänemark": "Denmark",
    "norwegen": "Norway",
    "finnland": "Finland",
    "polen": "Poland",
    "oesterreich": "Austria",
    "österreich": "Austria",
    "schweiz": "Switzerland",
    "ungarn": "Hungary",
    "rumaenien": "Romania",
    "rumänien": "Romania",
    "serbien": "Serbia",
    "albanien": "Albania",
    "griechenland": "Greece",
    "aegypten": "Egypt",
    "ägypten": "Egypt",
    "tunesien": "Tunisia",
    "algerien": "Algeria",
    "nigeria": "Nigeria",
    "ghana": "Ghana",
    "kamerun": "Cameroon",
    "senegal": "Senegal",
    "elfenbeinküste": "Ivory Coast",
    "elfenbeinkueste": "Ivory Coast",
    "suedafrika": "South Africa",
    "südafrika": "South Africa",
    "ukraine": "Ukraine",
    "russland": "Russia",
    "weissrussland": "Belarus",
    "weißrussland": "Belarus",
    "tschechien": "Czech Republic",
    "tschechische republik": "Czech Republic",
    "slowakei": "Slovakia",
    "slowenien": "Slovenia",
    "kroatien": "Croatia",
    "bosnien": "Bosnia and Herzegovina",
    "bosnien und herzegowina": "Bosnia and Herzegovina",
    "albanien": "Albania",
    "kosovo": "Kosovo",
    "moldau": "Moldova",
    "island": "Iceland",
    "island": "Iceland",
    "faroer": "Faroe Islands",
    "färöer": "Faroe Islands",
    "andorra": "Andorra",
    "san marino": "San Marino",
    "gibraltar": "Gibraltar",
    "liechtenstein": "Liechtenstein",
    "luxemburg": "Luxembourg",
    "malta": "Malta",
    "zypern": "Cyprus",
    "israel": "Israel",
    "tuerkei": "Turkey",
    "irak": "Iraq",
    "iran": "Iran",
    "saudi arabien": "Saudi Arabia",
    "katar": "Qatar",
    "vereinigte arabische emirate": "United Arab Emirates",
    "oman": "Oman",
    "jemen": "Yemen",
    "jordanien": "Jordan",
    "israel": "Israel",
    "libanon": "Lebanon",
    "syrien": "Syria",
    "thailand": "Thailand",
    "vietnam": "Vietnam",
    "indonesien": "Indonesia",
    "malaysia": "Malaysia",
    "singapur": "Singapore",
    "philippinen": "Philippines",
    "indien": "India",
    "pakistan": "Pakistan",
    "bangladesch": "Bangladesh",
    "sri lanka": "Sri Lanka",
    "korea": "South Korea",
    "korea dvr": "North Korea",
    "neuseeland": "New Zealand",
    "australien": "Australia",
    "honduras": "Honduras",
    "costa rica": "Costa Rica",
    "panama": "Panama",
    "jamaika": "Jamaika",
    "jamaika": "Jamaica",
    "haiti": "Haiti",
    "cuba": "Cuba",
    "kanada": "Canada",
    "usa": "United States",
    "vereinigte staaten": "United States",
    "bolivien": "Bolivia",
    "ecuador": "Ecuador",
    "ecuador": "Ecuador",
    "paraguay": "Paraguay",
    "uruguay": "Uruguay",
    "chile": "Chile",
    "peru": "Peru",
    "venezuela": "Venezuela",
    "brasilien": "Brazil",
    "argentinien": "Argentina",
    "kolumbien": "Colombia",
}
# Merge (überschreibt bestehende)
data["aliases"].update(new_aliases)

with open(p, "w", encoding="utf-8") as fh:
    json.dump(data, fh, separators=(",", ":"))
print(f"OK: {p} ({len(data['aliases'])} aliase)")
